//country name and population
//country name with currency symbol
var country=[
   {"name":{"common":"Ecuador","official":"Republic of Ecuador","nativeName":{"spa":{"official":"República del Ecuador","common":"Ecuador"}}},"tld":[".ec"],"cca2":"EC","ccn3":"218","cca3":"ECU","cioc":"ECU","independent":true,"status":"officially-assigned","unMember":true,"currencies":{"USD":{"name":"United States dollar","symbol":"$"}},"idd":{"root":"+5","suffixes":["93"]},"capital":["Quito"],"altSpellings":["EC","Republic of Ecuador","República del Ecuador"],"region":"Americas","subregion":"South America","languages":{"spa":"Spanish"},"translations":{"ces":{"official":"Ekvádorská republika","common":"Ekvádor"},"cym":{"official":"Gweriniaeth Ecwador","common":"Ecwador"},"deu":{"official":"Republik Ecuador","common":"Ecuador"},"est":{"official":"Ecuadori Vabariik","common":"Ecuador"},"fin":{"official":"Ecuadorin tasavalta","common":"Ecuador"},"fra":{"official":"République de l'Équateur","common":"Équateur"},"hrv":{"official":"Republika Ekvador","common":"Ekvador"},"hun":{"official":"Ecuadori Köztársaság","common":"Ecuador"},"ita":{"official":"Repubblica dell'Ecuador","common":"Ecuador"},"jpn":{"official":"エクアドル共和国","common":"エクアドル"},"kor":{"official":"에콰도르 공화국","common":"에콰도르"},"nld":{"official":"Republiek Ecuador","common":"Ecuador"},"per":{"official":"جمهوری اکوادور","common":"اکوادور"},"pol":{"official":"Ekwador","common":"Ekwador"},"por":{"official":"República do Equador","common":"Equador"},"rus":{"official":"Республика Эквадор","common":"Эквадор"},"slk":{"official":"Ekvádorská republika","common":"Ekvádor"},"spa":{"official":"República del Ecuador","common":"Ecuador"},"swe":{"official":"Republiken Ecuador","common":"Ecuador"},"urd":{"official":"جمہوریہ ایکوڈور","common":"ایکواڈور"},"zho":{"official":"厄瓜多尔共和国","common":"厄瓜多尔"}},"latlng":[-2.0,-77.5],"landlocked":false,"borders":["COL","PER"],"area":276841.0,"demonyms":{"eng":{"f":"Ecuadorean","m":"Ecuadorean"},"fra":{"f":"Équatorienne","m":"Équatorien"}},"flag":"\uD83C\uDDEA\uD83C\uDDE8","maps":{"googleMaps":"https://goo.gl/maps/TbX8hUW4gcbRPZiK7","openStreetMaps":"https://www.openstreetmap.org/relation/108089"},"population":17643060,"flags":{"svg":"https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
   "png":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/320px-Flag_of_Ecuador.svg.png"}},
   {"name":{"common":"Cayman Islands","official":"Cayman Islands","nativeName":{"eng":{"official":"Cayman Islands","common":"Cayman Islands"}}},"tld":[".ky"],"cca2":"KY","ccn3":"136","cca3":"CYM","cioc":"CAY","independent":false,"status":"officially-assigned","unMember":false,"currencies":{"USD":{"name":"Cayman Islands dollar","symbol":"$"}},"idd":{"root":"+1","suffixes":["345"]},"capital":["George Town"],"altSpellings":["KY"],"region":"Americas","subregion":"Caribbean","languages":{"eng":"English"},"translations":{"ces":{"official":"Kajmanské ostrovy","common":"Kajmanské ostrovy"},"cym":{"official":"Ynysoedd Cayman","common":"Ynysoedd Cayman"},"deu":{"official":"Cayman-Inseln","common":"Kaimaninseln"},"est":{"official":"Kaimanisaared","common":"Kaimanisaared"},"fin":{"official":"Caymansaaret","common":"Caymansaaret"},"fra":{"official":"Îles Caïmans","common":"Îles Caïmans"},"hrv":{"official":"Kajmanski otoci","common":"Kajmanski otoci"},"hun":{"official":"Kajmán-szigetek","common":"Kajmán-szigetek"},"ita":{"official":"Isole Cayman","common":"Isole Cayman"},"jpn":{"official":"ケイマン諸島","common":"ケイマン諸島"},"kor":{"official":"케이맨 제도","common":"케이맨 제도"},"nld":{"official":"Caymaneilanden","common":"Caymaneilanden"},"per":{"official":"جزایر کیمن","common":"جزایر کیمن"},"pol":{"official":"Kajmany","common":"Kajmany"},"por":{"official":"Ilhas Cayman","common":"Ilhas Caimão"},"rus":{"official":"Каймановы острова","common":"Каймановы острова"},"slk":{"official":"Kajmanie ostrovy","common":"Kajmanie ostrovy"},"spa":{"official":"Islas Caimán","common":"Islas Caimán"},"swe":{"official":"Caymanöarna","common":"Caymanöarna"},"urd":{"official":"جزائر کیمین","common":"جزائر کیمین"},"zho":{"official":"开曼群岛","common":"开曼群岛"}},"latlng":[19.5,-80.5],"landlocked":false,"area":264.0,"demonyms":{"eng":{"f":"Caymanian","m":"Caymanian"},"fra":{"f":"Caïmanienne","m":"Caïmanien"}},"flag":"\uD83C\uDDF0\uD83C\uDDFE","maps":{"googleMaps":"https://goo.gl/maps/P3ZVXX3LH63t91hL8","openStreetMaps":"https://www.openstreetmap.org/relation/7269765"},
   "population":65720}
]
// //countryname
// console.log(country[0].name["common"]);

// console.log(country[0].population);
// //country name with currency symbol
// console.log(country[0].currencies["USD"].symbol);
var symbol=country.map(region=>region.currencies["USD"]["symbol"])
console.log(symbol);
